use adventure_works;
-- drop table Products;
CREATE TABLE Products (
    ProductKey INT PRIMARY KEY,
    UnitPrice DECIMAL(10, 2),
    ProductAlternateKey VARCHAR(50),
    ProductSubcategoryKey INT,
    WeightUnitMeasureCode VARCHAR(10),
    SizeUnitMeasureCode VARCHAR(10),
    EnglishProductName VARCHAR(255),
    SpanishProductName VARCHAR(255),
    FrenchProductName VARCHAR(255),
    StandardCost DECIMAL(10, 2),
    FinishedGoodsFlag BOOLEAN,
    Color VARCHAR(50),
    SafetyStockLevel INT,
    ReorderPoint INT,
    ListPrice DECIMAL(10, 2),
    Size VARCHAR(50),
    SizeRange VARCHAR(50),
    Weight DECIMAL(10, 2),
    DaysToManufacture INT,
    ProductLine VARCHAR(50),
    DealerPrice DECIMAL(10, 2),
    Class VARCHAR(50),
    Style VARCHAR(50),
    ModelName VARCHAR(255),
    EnglishDescription TEXT,
    FrenchDescription TEXT,
    ChineseDescription TEXT,
    ArabicDescription TEXT,
    HebrewDescription TEXT,
    ThaiDescription TEXT,
    GermanDescription TEXT,
    JapaneseDescription TEXT,
    TurkishDescription TEXT,
    StartDate  VARCHAR(50),
    EndDate  VARCHAR(50),
    Status VARCHAR(20)
);